# Generated by Django 4.2.30 on 2026-05-21 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ReceiptSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_name', models.CharField(default='Hamro Mart', max_length=200)),
                ('address', models.TextField(default='Kathmandu, Nepal')),
                ('phone', models.CharField(default='+977-1-4XXXXXX', max_length=50)),
                ('pan_number', models.CharField(blank=True, max_length=50, null=True, verbose_name='VAT/PAN Number')),
                ('header_message', models.TextField(blank=True, default='Thank you for shopping with us!', null=True)),
                ('footer_message', models.TextField(blank=True, default='Exchange within 7 days with invoice.', null=True)),
            ],
            options={
                'verbose_name': 'Receipt Setting',
                'verbose_name_plural': 'Receipt Settings',
            },
        ),
    ]
